- app/models/user.rb
- db/migrate/20190331073032_create_users.rb
- db/schema.rb
- test/fixtures/users.yml
- test/models/user_test.rb
> do rails generate model user name:string password:string

- db/migrate/20190331090111_add_picture_to_posts.rb
- db/schema.rb
> rails g migration AddPictureToPosts picture:string でpostsモデルにカラムを追加

- app/assets/javascripts/user.coffee
- app/assets/stylesheets/user.scss
- app/controllers/user_controller.rb
- app/helpers/user_helper.rb
- app/views/user/new.html.erb
- config/routes.rb
- test/controllers/user_controller_test.rb
> do rails g controller user new

- app/controllers/user_controller.rb
- app/views/user/login.html.erb
- config/routes.rb
> [add] user's login page

- app/controllers/user_controller.rb
- app/views/user/edit.html.erb
- app/views/user/login.html.erb
- config/routes.rb
> [add] user's edit page

- app/controllers/posts_controller.rb
- app/controllers/user_controller.rb
- app/views/posts/edit.html.erb
- app/views/user/create.html.erb
- config/routes.rb
> Create post edit page

- app/controllers/posts_controller.rb
- app/views/posts/data.html.erb
- app/views/posts/edit.html.erb
- config/routes.rb
> add post's data page

- Gemfile
- Gemfile.lock
- app/controllers/user_controller.rb
- app/views/user/new.html.erb
- config/routes.rb
> Edit user login page

- app/controllers/user_controller.rb
- config/routes.rb
#24's task is done !!
Please check!
> [add] ユーザー登録のときのエラー処理を記述した

- app/controllers/user_controller.rb
- app/views/user/index.html.erb
- config/routes.rb
I make user index page. Prease check this pull request!
> [add] Can look user index page

- app/controllers/posts_controller.rb
- app/views/posts/show.html.erb
- config/routes.rb
#30 's task is done!!
Please check
>  add post's show page

- app/controllers/application_controller.rb
- app/views/layouts/application.html.erb
> Make header

- app/controllers/user_controller.rb
> renderをredirect_toに変更した

- app/controllers/user_controller.rb
- app/views/layouts/application.html.erb
- config/routes.rb
> [add] logout機能を実装した

- app/models/post.rb
> add validates

- app/models/user.rb
> add varidates about user

- app/views/layouts/application.html.erb
> add header for pre login status

- app/controllers/user_controller.rb
- app/views/user/new.html.erb
> appear the error message

- config/routes.rb
> fix first load url

- app/views/posts/index.html.erb
- app/views/posts/show.html.erb
- config/routes.rb
> 投稿データを詳しく見れるようにした

- app/controllers/user_controller.rb
- app/views/user/login_form.html.erb
- app/views/user/new.html.erb
- db/migrate/20190419120315_add_mail_address_to_users.rb
- db/schema.rb
> Add email data

- app/controllers/user_controller.rb
> エラーメッセージを修正した

- app/controllers/posts_controller.rb
- app/views/posts/new.html.erb
- config/routes.rb
> Post error message

- app/controllers/posts_controller.rb
- app/views/posts/edit.html.erb
- app/views/posts/show.html.erb
- config/routes.rb
> Make post edit page

- app/controllers/user_controller.rb
- app/views/user/edit.html.erb
- app/views/user/index.html.erb
- app/views/user/show.html.erb
- config/routes.rb
> Make user edit page

- test/fixtures/posts.yml
- test/fixtures/users.yml
> Make test db

- app/controllers/application_controller.rb
- app/controllers/posts_controller.rb
> 権限付与のバグを直した

- app/controllers/application_controller.rb
- app/controllers/user_controller.rb
> 他のuserをeditできるガバを修正した

- app/views/user/show.html.erb
> link_toをリファクタリングした

- app/views/posts/show.html.erb
> link_toのリファクタリングをした

- app/views/user/index.html.erb
> userの画像を表示させるようにした

- app/controllers/user_controller.rb
- app/views/user/new.html.erb
> errorメッセージを表示させるようにした

- app/models/user.rb
> 重複するemailを弾くvalidationを追加した

- app/controllers/posts_controller.rb
- app/views/posts/show.html.erb
- config/routes.rb
> 投稿削除機能を作成した

- app/controllers/posts_controller.rb
- app/controllers/user_controller.rb
- app/views/posts/index.html.erb
- app/views/posts/show.html.erb
- app/views/user/edit.html.erb
- app/views/user/index.html.erb
- app/views/user/show.html.erb
> fix user images

- Gemfile
- app/controllers/user_controller.rb
- app/models/user.rb
- db/migrate/20190504092338_change_users_columns.rb
- db/schema.rb
> passwordをhash化した

- .gitignore
- README.md
READMEと.gitignoreを更新しました。確認お願いします。
> update readme and .gitignore

- app/controllers/auction_controller.rb
- app/views/posts/show.html.erb
> 入札周りのロジック改善(#120)
